services:
  postgres:
    image: postgres:16-alpine
    container_name: aml-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: aml_db
      POSTGRES_USER: aml_user
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aml_user -d aml_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
